import type { WatchItem } from '../types/watchlog';

/**
 * Seed watchlist with real TMDB / Open Library metadata and cover URLs.
 * Images load immediately — no API call required on first render.
 */
export const mockWatchlist: WatchItem[] = [
  {
    id: 'movie-inception',
    externalId: '27205',
    type: 'movie',
    title: 'Inception',
    genres: ['Sci-Fi', 'Action'],
    status: 'watching',
    rating: null,
    dateAdded: '2026-02-01T10:00:00Z',
    dateCompleted: null,
    releaseYear: 2010,
    posterUrl: 'https://image.tmdb.org/t/p/w500/xlaY2zyzMfkhk0HSC5VUwzoZPU1.jpg',
  },
  {
    id: 'movie-interstellar',
    externalId: '157336',
    type: 'movie',
    title: 'Interstellar',
    genres: ['Sci-Fi', 'Drama'],
    status: 'want',
    rating: null,
    dateAdded: '2026-03-01T10:00:00Z',
    dateCompleted: null,
    releaseYear: 2014,
    posterUrl: 'https://image.tmdb.org/t/p/w500/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg',
  },
  {
    id: 'book-dune',
    externalId: 'OL893414W',
    type: 'book',
    title: 'Dune',
    author: 'Frank Herbert',
    genres: ['Sci-Fi'],
    status: 'reading',
    rating: null,
    dateAdded: '2026-02-05T10:00:00Z',
    dateCompleted: null,
    publishYear: 1965,
    coverUrl: 'https://covers.openlibrary.org/b/id/11481354-L.jpg',
  },
  {
    id: 'book-gatsby',
    externalId: 'OL468431W',
    type: 'book',
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    genres: ['Fiction', 'Classic'],
    status: 'done',
    rating: 4,
    dateAdded: '2026-01-20T10:00:00Z',
    dateCompleted: '2026-01-25T10:00:00Z',
    publishYear: 1925,
    coverUrl: 'https://covers.openlibrary.org/b/id/10590366-L.jpg',
  },
  {
    id: 'movie-fight-club',
    externalId: '550',
    type: 'movie',
    title: 'Fight Club',
    genres: ['Drama', 'Thriller'],
    status: 'done',
    rating: 5,
    dateAdded: '2026-01-10T10:00:00Z',
    dateCompleted: '2026-01-15T10:00:00Z',
    releaseYear: 1999,
    posterUrl: 'https://image.tmdb.org/t/p/w500/jSziioSwPVrOy9Yow3XhWIBDjq1.jpg',
  },
  {
    id: 'movie-dark-knight',
    externalId: '155',
    type: 'movie',
    title: 'The Dark Knight',
    genres: ['Action', 'Crime', 'Drama'],
    status: 'want',
    rating: null,
    dateAdded: '2026-03-10T10:00:00Z',
    dateCompleted: null,
    releaseYear: 2008,
    posterUrl: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
  },
  {
    id: 'book-hail-mary',
    externalId: 'OL21745884W',
    type: 'book',
    title: 'Project Hail Mary',
    author: 'Andy Weir',
    genres: ['Sci-Fi'],
    status: 'want',
    rating: null,
    dateAdded: '2026-03-12T10:00:00Z',
    dateCompleted: null,
    publishYear: 2021,
    coverUrl: 'https://covers.openlibrary.org/b/id/11200092-L.jpg',
  },
  {
    id: 'book-1984',
    externalId: 'OL1168083W',
    type: 'book',
    title: 'Nineteen Eighty-Four',
    author: 'George Orwell',
    genres: ['Fiction', 'Dystopian'],
    status: 'reading',
    rating: null,
    dateAdded: '2026-02-20T10:00:00Z',
    dateCompleted: null,
    publishYear: 1949,
    coverUrl: 'https://covers.openlibrary.org/b/id/9267242-L.jpg',
  },
];

/** Empty list — useful for edge-case tests */
export const emptyWatchlist: WatchItem[] = [];

/** Items without cover URLs — for enrichment tests only */
export const watchlistMissingImages: WatchItem[] = [
  {
    id: 'movie-no-poster',
    externalId: '27205',
    type: 'movie',
    title: 'Inception',
    genres: ['Sci-Fi'],
    status: 'want',
    rating: null,
    dateAdded: '2026-01-01T10:00:00Z',
    dateCompleted: null,
    releaseYear: 2010,
    posterUrl: null,
  },
  {
    id: 'book-no-cover',
    externalId: 'OL893414W',
    type: 'book',
    title: 'Dune',
    author: 'Frank Herbert',
    genres: ['Sci-Fi'],
    status: 'want',
    rating: null,
    dateAdded: '2026-01-01T10:00:00Z',
    dateCompleted: null,
    publishYear: 1965,
    coverUrl: null,
  },
];
